### ISSUE TITLE
PhantomJS/SlimerJS custom launcher never closes on Linux

### ISSUE THREAD

**Issue by EWhite613** [testem/testem#915]
It justs sits in limbo for ever. If I run a callback that closes phantomjs on `Testem.afterTests` I get `"phantomjs custom-launcher <url>" exited unexpectedly with exit code <int>`

Custom Launcher:

```javascript
'use strict'
var system = require('system')
var fs = require('fs')
var page = require('webpage').create()
var url = system.args[1]
page.viewportSize = {
  width: 1024,
  height: 768
}

setTimeout(function() {
  page.open(url, function (status) {
    page.evaluate(function(s) {
       Testem.afterTests(
      //Asynchronously
      function(config, data, callback) {
        setTimeout( function (params) {
          var status = window.callPhantom({
            command: 'exit',
            reason:  'User Request.'
          })
        }, 1000)
    })
    })
  })
   
  page.onCallback = function(data) {
    if (data && data.command && (data.command === 'exit')) {
      if (data.reason) console.log('web page requested exit: '+data.reason);
        phantom.exit(1);
    }
    console.log('CALLBACK: ' + JSON.stringify(data))
      // Prints 'CALLBACK: { "hello": "world" }'
    var bb = page.evaluate(function() {
      return document.getElementById('ember-testing-container').getBoundingClientRect()
    })
    console.log(bb)
    page.clipRect = {
      top: bb.top,
      left: bb.left,
      width: bb.width,
      height: bb.height
    }
    return page.renderBase64('PNG')
  }

  page.onError = function(msg, trace) {
    console.log(msg)
    trace.forEach(function(item) {
      console.log('  ', item.file, ':', item.line)
    })
  }
}, 1000);
```

**Comment by johanneswuerbach** [comment]
Not in front of a computer atm, but looks like you are never calling the afterTests callback, may that be the issue?

**Comment by EWhite613** [comment]
@johanneswuerbach I'm hitting it. Only way to hit `phantom.exit(1)` is from that callback. But I fail my tests because I get the error `"phantomjs custom-launcher <url>" exited unexpectedly with exit code <int>`

**Comment by EWhite613** [comment]
Testem.js:
```javascript
module.exports = {
  'framework': 'mocha',
  'test_page': 'tests/index.html?hidepassed',
  'disable_watching': true,
  'launch_in_ci': [
    'PhantomJsVisualAcceptance'
  ],
  'launch_in_dev': [
    'Firefox'
  ],
  'launchers': {
    'PhantomJsVisualAcceptance': {
      'command': 'phantomjs vendor/phantomjs-launcher.js <url>',
      'protocol': 'browser'
    }
  }
}

```

Maybe my `Testem.js` has the issue? None that I can see though.

**Comment by EWhite613** [comment]
@johanneswuerbach 
There has to be something I'm missing on writing a custom launcher.

If I simplify a launcher to just : https://github.com/testem/testem/blob/master/assets/phantom.js

and use the launcher as:
```json
{
  "framework": "mocha",
  "test_page": "tests/index.html?hidepassed&coverage",
  "disable_watching": true,
  "launch_in_ci": [
	"launcher"
  ],
  "launch_in_dev": [
	"Chrome"
  ],
  "launchers": {
    "launcher": {
      "command": "phantomjs launcher.js <url>",
      "protocol": "browser"
    }
  }
}
```

**Comment by EWhite613** [comment]
'Fixed' by doing:
```javascript
  page.open(url, function (status) {
    page.evaluate(function(s) {
       Testem.afterTests(
      //Asynchronously
      function(config, data, callback) {
          callback(null)
        
        setTimeout( function (params) {
          var status = window.callPhantom({
            command: 'exit',
            reason:  'transport close'
          })
        }, 2000)
    })
    })
```

`callback(null)` by itself yields no results on Linux. Just get:

```bash
  socket.io-parser decoded 2["after-tests-complete"] as {"type":2,"nsp":"/","data":["after-tests-complete"]} +0ms
  socket.io:socket got packet {"type":2,"nsp":"/","data":["after-tests-complete"]} +1ms
  socket.io:socket emitting event ["after-tests-complete"] +0ms
  <repeat continuously forever>
  engine:ws received "2" +24s
  engine:socket packet +2ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +1ms
  engine:ws writing "3" +0ms
 </repeat>

```

 But doing `callback(nulll)` then exiting phantomjs after 2 secs works (1 second is to early and results in `exited unexpectedly with exit code `). Closing phantomjs results in receiving the `"42["all-test-results",...` packet, but somehow the prev `callback(null)` prevents the failed test `"phantomjs custom-launcher <url>" exited unexpectedly with exit code <int>`.

**Comment by EWhite613** [comment]
With a custom launcher (only tried phantomjs, SlimerJS ) the proccess doesn't actually get killed in https://github.com/testem/testem/blob/371cd22890f5c79a1ce0ed6f4da51d63bd636dff/lib/runners/browser_test_runner.js#L242-L259

**Comment by mlunoe** [comment]
Using the asynchronous API (`afterTests`), when running my slimerjs-launcher, did not work for me.
I would see `afterTests` being called before I would be able to register my listener, so I had to register with the `iframe`, since I could see that would still receive messages. Here is my "solution", which is still fragile, since it might still not register in time:
```js
const system = require('system');
const page = require('webpage').create();
const url = system.args[1];

page.viewportSize = { width: 1000, height: 800 };

// Open web page
page.open(url, function() {
  page.evaluate(function() {
    // Register to listen for when tests are done
    const iframe = document.querySelector('iframe[src*="connection.html"]');
    iframe.contentWindow.addEventListener(
      'message',
      function(event) {
        if (event.origin !== iframe.contentWindow.location.origin) {
          // ignore messages not from the iframe
          return;
        }

        const message = Testem.deserializeMessage(event.data);
        if (message.data[0] === 'all-test-results' || message.data[0] === 'tap-all-test-results') {
          // Set time to wait for callback to finish its work. Then close launcher
          // (Issue Testem: fails to close custom launcher on Linux) https://github.com/testem/testem/issues/915
          // For more information, see https://docs.slimerjs.org/current/api/webpage.html#oncallback
          setTimeout(function() {
            window.callPhantom({ command: 'exit', reason: 'transport close' });
          }, 2000);
        }
      },
      false
    );
  });
});

// Pass on any messages received
page.onConsoleMessage = function(msg) {
  console.log(`console: ${msg}`);
};

page.onCallback = function(data) {
  if (data && data.command && data.command === 'exit') {
    if (data.reason) {
      console.log(`Web page requested exit: ${data.reason}`);
    }

    // Necessary to ensure browser window closes when done
    // For more information, see https://docs.slimerjs.org/current/quick-start.html#hello-world
    slimer.exit(0);
  }
};

// Print error messages
page.onError = function(msg, trace) {
  console.error(msg);
  trace.forEach(function(item) {
    console.error('  ', item.file, ':', item.line);
  });
};
```

I would be nice if there was some way of telling whether the tests are already done, or it would just call the `afterTests` immediately if it was done running.
